#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("zalculus.Resource", IsApplication=true)]

namespace zalculus
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int zalculus = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060003
			public const int buttonClear = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int buttonDele = 2131099652;
			
			// aapt resource value: 0x7f060015
			public const int buttonDevide = 2131099669;
			
			// aapt resource value: 0x7f060012
			public const int buttonDot = 2131099666;
			
			// aapt resource value: 0x7f06000f
			public const int buttonEight = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int buttonEquel = 2131099668;
			
			// aapt resource value: 0x7f06000b
			public const int buttonFive = 2131099659;
			
			// aapt resource value: 0x7f06000a
			public const int buttonFour = 2131099658;
			
			// aapt resource value: 0x7f06000d
			public const int buttonMinus = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int buttonMultiple = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int buttonNine = 2131099664;
			
			// aapt resource value: 0x7f060006
			public const int buttonOne = 2131099654;
			
			// aapt resource value: 0x7f060009
			public const int buttonPlus = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int buttonSeven = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int buttonSix = 2131099660;
			
			// aapt resource value: 0x7f060008
			public const int buttonThree = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int buttonTwo = 2131099655;
			
			// aapt resource value: 0x7f060013
			public const int buttonZero = 2131099667;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout2 = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout3 = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int textView1 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Main = 2130968576;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
